#!/bin/sh
# Run this in the directory as sudo where you want SheepDa installed
 
git clone https://github.com/138paulmiller/SheepDa.git
cd SheepDa
echo export SHEEPDA=$(pwd) >> ~/.bashrc
echo export 'PATH=$PATH:$SHEEPDA' >> ~/.bashrc
 
 
